language: node_js
sudo: required
services:
  -docker

before install:
  - docker build -t docker-cheat -f Dockerfile.dev .

script:
  - docker run docker-cheat npm run test -- --coverage
  ## docker run image_ID/name npm run test -- --coverage
