version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    # restart: on-failure will work only when containers crash with a error status code !=0 , error=0 meann we crashed intentinally. It is not on-failure 
    build: .
    ports:
      - "8080:8080"


# docker build -t docker_or_repository_id/app_name_or_build_context_or_folder:version .
# docker run -p 8080:8080 docker_or_repository_id/app_name_or_build_context_or_folder:version
# Equivalent in Docker-Compose both command one after another : docker-compose up --build


# docker run -p 8080:8080 docker_or_repository_id/app_name_or_build_context_or_folder:version
# Equivalent in Docker-Compose : docker-compose up


# MY MACHINE/LOCALHOST PORT : CONTAINER PORT
