apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: server
  template:
    metadata:
      labels: 
        component: server
    spec:
      containers:
        - name: server
          image: knsakib/express-api-server
          ports: 
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service 
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres 
              # it is the default database used by default user.
              # may not good in prod for security. May be good idea 
              # to put into K8s secret alongside the password  
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
                  #This is the key we created in the secret by imperative decleration 
